# TODO: replace the base image to Alpine Linux for better consistency, given
# that the image to run training/inferencing scripts is based on Alpine Linux
FROM --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/base:debian
